### ISSUE TITLE
Error compiling on Windows

### ISSUE THREAD

**Issue by jzhang1** [likr/rust-webgl2-example#1]
I'm getting the following error trying to build the project on Windows
   Compiling emscripten-sys v0.3.2
error: failed to run custom build command for `emscripten-sys v0.3.2`
process didn't exit successfully: `C:\Users\jzhan\Downloads\rust-webgl2-example-master\rust-webgl2-example-master\target\release\build\emscripten-sys-4fbaa9c282267630\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at '#include <...> search starts here:', src\libcore\option.rs:839:4
stack backtrace:
   0:     0x7ff7424be361 - std::sys_common::backtrace::_print
                               at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1:     0x7ff7424c87cc - std::panicking::default_hook::{{closure}}
                               at C:\projects\rust\src\libstd\panicking.rs:380
   2:     0x7ff7424c84b5 - std::panicking::default_hook
                               at C:\projects\rust\src\libstd\panicking.rs:397
   3:     0x7ff7424c8da5 - std::panicking::rust_panic_with_hook
                               at C:\projects\rust\src\libstd\panicking.rs:577
   4:     0x7ff7424c8c38 - std::panicking::begin_panic<alloc::string::String>
                               at C:\projects\rust\src\libstd\panicking.rs:538
   5:     0x7ff7424c8b11 - std::panicking::begin_panic_fmt
                               at C:\projects\rust\src\libstd\panicking.rs:522
   6:     0x7ff7424c8a7f - std::panicking::rust_begin_panic
                               at C:\projects\rust\src\libstd\panicking.rs:498
   7:     0x7ff7424d0fae - core::panicking::panic_fmt
                               at C:\projects\rust\src\libcore\panicking.rs:71
   8:     0x7ff7424d101f - core::option::expect_failed
                               at C:\projects\rust\src\libcore\option.rs:839
   9:     0x7ff7422e40ea - clang_sys::support::Clang::find::h9d3438fa2c51c053
  10:     0x7ff7422e19ed - aster::AstBuilder::item::hb8b47eede540a78b
  11:     0x7ff7422e2a6c - clang_sys::support::Clang::find::h9d3438fa2c51c053
  12:     0x7ff74224b002 - bindgen::Bindings::generate::h6ed0a2bf1b5938b7
  13:     0x7ff74224ade6 - bindgen::Builder::generate::had19a6aff5fbd822
  14:     0x7ff7421ce6ae - ZIG_NORM_F
  15:     0x7ff7424c9ea1 - panic_unwind::__rust_maybe_catch_panic
                               at C:\projects\rust\src\libpanic_unwind\lib.rs:99
  16:     0x7ff7424c95c1 - std::rt::lang_start
                               at C:\projects\rust\src\libstd\rt.rs:52
  17:     0x7ff7424d7df8 - __scrt_common_main_seh
                               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  18:     0x7ffad7af2773 - BaseThreadInitThunk

I'm using rustc 1.20.0, and emscripten-sdk-1.37.21-64bit.

**Comment by likr** [comment]
Hi,

Now, I have updated the project.
Probably, the problem on building emscripten-sys was solved.
