### ISSUE TITLE
Error compiling 

### ISSUE THREAD

**Issue by phocks** [likr/rust-webgl2-example#2]
I'm getting:
```
Compiling emscripten-sys v0.3.2
error: failed to run custom build command for `emscripten-sys v0.3.2`
process didn't exit successfully: `/Users/phocks/Sites/rust-webgl2-example/target/release/build/emscripten-sys-ccab12d2ee5cbee0/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'failed to get envvar EMSCRIPTEN: NotPresent', src/libcore/result.rs:860:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
I'm on macOS Sierra and have successfully compiled and run through this guide https://medium.com/@ianjsikes/get-started-with-rust-webassembly-and-webpack-58d28e219635

**Comment by likr** [comment]
Hi,

I couldn't reproduce the error on macOS.
Probably, you didn't set the environment variables for emscripten correctly.
Did you execute following command?

```console
$ source path/to/emsdk/emsdk_env.sh
```

**Comment by gardell** [comment]
https://github.com/gifnksm/emscripten-sys/issues/6 might help

**Comment by eloraiby** [comment]
I have the same problem on linux. Were you able to fix it ?

**Comment by matiaslindgren** [comment]
I encountered the same problem on Ubuntu 18.04. Running `./emsdk activate latest` before `source ./emsdk/emsdk_env.sh` creates an emscripten configuration file, which enables all emscripten environment variables.

More info here: https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html

**Comment by likr** [comment]
Hi all,

I have updated this example so that it does not depend on emscripten-sys.
If you are still interested, please try the new version.
