### ISSUE TITLE
Uncaught (in promise) ReferenceError: _setThrew is not defined

### ISSUE THREAD

**Issue by NielsSkovgaard** [likr/rust-webgl2-example#3]
Hello,
I run with "npm start" and get the following console errors in Google Chrome.
Any ideas how to solve this?

Best regards,
Niels Skovgaard

rust-webgl2-example.js:formatted:1261
ERROR: unsupported shader version

rust-webgl2-example.js:formatted:1261 

rust-webgl2-example.js:formatted:1278
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
put_char @ rust-webgl2-example.js:formatted:1278
write @ rust-webgl2-example.js:formatted:1197
write @ rust-webgl2-example.js:formatted:3395
___syscall4 @ rust-webgl2-example.js:formatted:4331
(anonymous) @ wasm-000a5f6e-268:20
(anonymous) @ wasm-000a5f6e-292:29
(anonymous) @ wasm-000a5f6e-604:14
(anonymous) @ wasm-000a5f6e-244:642
(anonymous) @ wasm-000a5f6e-448:10
Module.dynCall_iiii @ rust-webgl2-example.js:formatted:7334
invoke_iiii @ rust-webgl2-example.js:formatted:6944
(anonymous) @ wasm-000a5f6e-309:40
(anonymous) @ wasm-000a5f6e-614:68
(anonymous) @ wasm-000a5f6e-439:10
Module.dynCall_viii @ rust-webgl2-example.js:formatted:7362
invoke_viii @ rust-webgl2-example.js:formatted:7021
(anonymous) @ wasm-000a5f6e-619:535
(anonymous) @ wasm-000a5f6e-293:216
(anonymous) @ wasm-000a5f6e-438:11
Module.dynCall_viiii @ rust-webgl2-example.js:formatted:7366
invoke_viiii @ rust-webgl2-example.js:formatted:7032
(anonymous) @ wasm-000a5f6e-356:78
(anonymous) @ wasm-000a5f6e-238:43
(anonymous) @ wasm-000a5f6e-223:65
(anonymous) @ wasm-000a5f6e-386:132
(anonymous) @ wasm-000a5f6e-361:8
(anonymous) @ wasm-000a5f6e-538:14
(anonymous) @ wasm-000a5f6e-443:8
Module.dynCall_vi @ rust-webgl2-example.js:formatted:7350
invoke_vi @ rust-webgl2-example.js:formatted:6988
(anonymous) @ wasm-000a5f6e-536:7
(anonymous) @ wasm-000a5f6e-539:70
(anonymous) @ wasm-000a5f6e-397:13
Module._main @ rust-webgl2-example.js:formatted:7298
callMain @ rust-webgl2-example.js:formatted:7404
doRun @ rust-webgl2-example.js:formatted:7446
run @ rust-webgl2-example.js:formatted:7458
runCaller @ rust-webgl2-example.js:formatted:7388
removeRunDependency @ rust-webgl2-example.js:formatted:610
receiveInstance @ rust-webgl2-example.js:formatted:669
receiveInstantiatedSource @ rust-webgl2-example.js:formatted:681
Promise.then (async)
instantiateArrayBuffer @ rust-webgl2-example.js:formatted:686
createWasm @ rust-webgl2-example.js:formatted:700
Module.asm @ rust-webgl2-example.js:formatted:713
(anonymous) @ rust-webgl2-example.js:formatted:7283
Show 11 more frames

rust-webgl2-example.js:formatted:1278
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
put_char @ rust-webgl2-example.js:formatted:1278
write @ rust-webgl2-example.js:formatted:1197
write @ rust-webgl2-example.js:formatted:3395
___syscall4 @ rust-webgl2-example.js:formatted:4331
(anonymous) @ wasm-000a5f6e-268:20
(anonymous) @ wasm-000a5f6e-292:29
(anonymous) @ wasm-000a5f6e-604:14
(anonymous) @ wasm-000a5f6e-244:642
(anonymous) @ wasm-000a5f6e-448:10
Module.dynCall_iiii @ rust-webgl2-example.js:formatted:7334
invoke_iiii @ rust-webgl2-example.js:formatted:6944
(anonymous) @ wasm-000a5f6e-309:40
(anonymous) @ wasm-000a5f6e-614:178
(anonymous) @ wasm-000a5f6e-439:10
Module.dynCall_viii @ rust-webgl2-example.js:formatted:7362
invoke_viii @ rust-webgl2-example.js:formatted:7021
(anonymous) @ wasm-000a5f6e-619:535
(anonymous) @ wasm-000a5f6e-293:216
(anonymous) @ wasm-000a5f6e-438:11
Module.dynCall_viiii @ rust-webgl2-example.js:formatted:7366
invoke_viiii @ rust-webgl2-example.js:formatted:7032
(anonymous) @ wasm-000a5f6e-356:78
(anonymous) @ wasm-000a5f6e-238:43
(anonymous) @ wasm-000a5f6e-223:65
(anonymous) @ wasm-000a5f6e-386:132
(anonymous) @ wasm-000a5f6e-361:8
(anonymous) @ wasm-000a5f6e-538:14
(anonymous) @ wasm-000a5f6e-443:8
Module.dynCall_vi @ rust-webgl2-example.js:formatted:7350
invoke_vi @ rust-webgl2-example.js:formatted:6988
(anonymous) @ wasm-000a5f6e-536:7
(anonymous) @ wasm-000a5f6e-539:70
(anonymous) @ wasm-000a5f6e-397:13
Module._main @ rust-webgl2-example.js:formatted:7298
callMain @ rust-webgl2-example.js:formatted:7404
doRun @ rust-webgl2-example.js:formatted:7446
run @ rust-webgl2-example.js:formatted:7458
runCaller @ rust-webgl2-example.js:formatted:7388
removeRunDependency @ rust-webgl2-example.js:formatted:610
receiveInstance @ rust-webgl2-example.js:formatted:669
receiveInstantiatedSource @ rust-webgl2-example.js:formatted:681
Promise.then (async)
instantiateArrayBuffer @ rust-webgl2-example.js:formatted:686
createWasm @ rust-webgl2-example.js:formatted:700
Module.asm @ rust-webgl2-example.js:formatted:713
(anonymous) @ rust-webgl2-example.js:formatted:7283
Show 11 more frames

rust-webgl2-example.js:formatted:7417
exception thrown: ReferenceError: _setThrew is not defined,ReferenceError: _setThrew is not defined
    at invoke_viiii (http://127.0.0.1:8080/rust-webgl2-example.js:1:159245)
    at wasm-function[356]:168
    at wasm-function[238]:97
    at wasm-function[223]:143
    at wasm-function[386]:276
    at wasm-function[361]:13
    at wasm-function[538]:27
    at wasm-function[443]:13
    at Module.dynCall_vi (http://127.0.0.1:8080/rust-webgl2-example.js:1:168224)
    at invoke_vi (http://127.0.0.1:8080/rust-webgl2-example.js:1:158488)
callMain @ rust-webgl2-example.js:formatted:7417
doRun @ rust-webgl2-example.js:formatted:7446
run @ rust-webgl2-example.js:formatted:7458
runCaller @ rust-webgl2-example.js:formatted:7388
removeRunDependency @ rust-webgl2-example.js:formatted:610
receiveInstance @ rust-webgl2-example.js:formatted:669
receiveInstantiatedSource @ rust-webgl2-example.js:formatted:681
Promise.then (async)
instantiateArrayBuffer @ rust-webgl2-example.js:formatted:686
createWasm @ rust-webgl2-example.js:formatted:700
Module.asm @ rust-webgl2-example.js:formatted:713
(anonymous) @ rust-webgl2-example.js:formatted:7283

rust-webgl2-example.js:formatted:7037
Uncaught (in promise) ReferenceError: _setThrew is not defined
    at invoke_viiii (rust-webgl2-example.js:formatted:7037)
    at :8080/wasm-function[356]:168
    at :8080/wasm-function[238]:97
    at :8080/wasm-function[223]:143
    at :8080/wasm-function[386]:276
    at :8080/wasm-function[361]:13
    at :8080/wasm-function[538]:27
    at :8080/wasm-function[443]:13
    at Module.dynCall_vi (rust-webgl2-example.js:formatted:7350)
    at invoke_vi (rust-webgl2-example.js:formatted:6988)
invoke_viiii @ rust-webgl2-example.js:formatted:7037
(anonymous) @ wasm-000a5f6e-356:78
(anonymous) @ wasm-000a5f6e-238:43
(anonymous) @ wasm-000a5f6e-223:65
(anonymous) @ wasm-000a5f6e-386:132
(anonymous) @ wasm-000a5f6e-361:8
(anonymous) @ wasm-000a5f6e-538:14
(anonymous) @ wasm-000a5f6e-443:8
Module.dynCall_vi @ rust-webgl2-example.js:formatted:7350
invoke_vi @ rust-webgl2-example.js:formatted:6988
(anonymous) @ wasm-000a5f6e-536:7
(anonymous) @ wasm-000a5f6e-539:70
(anonymous) @ wasm-000a5f6e-397:13
Module._main @ rust-webgl2-example.js:formatted:7298
callMain @ rust-webgl2-example.js:formatted:7404
doRun @ rust-webgl2-example.js:formatted:7446
run @ rust-webgl2-example.js:formatted:7458
runCaller @ rust-webgl2-example.js:formatted:7388
removeRunDependency @ rust-webgl2-example.js:formatted:610
receiveInstance @ rust-webgl2-example.js:formatted:669
receiveInstantiatedSource @ rust-webgl2-example.js:formatted:681
Promise.then (async)
instantiateArrayBuffer @ rust-webgl2-example.js:formatted:686
createWasm @ rust-webgl2-example.js:formatted:700
Module.asm @ rust-webgl2-example.js:formatted:713
(anonymous) @ rust-webgl2-example.js:formatted:7283

**Comment by NielsSkovgaard** [comment]
Looks like "invoke_viiii" calls "_setThrew" which is not defined, and this gives an error.

**Comment by likr** [comment]
@NielsSkovgaard Thank you for your report!

The API change in emscripten for creating webgl2 context has caused the error.
I have updated to use `EMCC_CFLAGS='-s USE_WEBGL2=1'` instead of `EmscriptenWebGLContextAttributes`.

**Comment by likr** [comment]
Sorry, `EmscriptenWebGLContextAttributes` was still needed.
I have just added `EMCC_CFLAGS='-s USE_WEBGL2=1'` in build command.
